// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuvnfzzsgxstemnztvel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1dm5menpzZ3hzdGVtbnp0dmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDY5MjksImV4cCI6MjA3MDYyMjkyOX0.dEslpJGKH9J-al6-XrH3nRLcZiHUvdb7mtE9F9n78VQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});