name: Hostinger Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy PHP files and .htaccess to dist
        run: |
          cp index.php dist/
          cp composer.json dist/
          cp composer.lock dist/
          cp public/.htaccess dist/
          # Ensure .htaccess is copied correctly
          ls -la dist/.htaccess
      - name: Verify build output
        run: |
          echo "Build directory contents (including hidden files):"
          ls -la dist/
          echo "Checking for required files:"
          test -f dist/index.html && echo "✓ index.html found" || echo "✗ index.html missing"
          test -f dist/index.php && echo "✓ index.php found" || echo "✗ index.php missing"
          test -f dist/.htaccess && echo "✓ .htaccess found" || echo "✗ .htaccess missing"
          echo "Contents of .htaccess file:"
          cat dist/.htaccess || echo "Could not read .htaccess"
      - name: Deploy to Hostinger via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          protocol: sftp
          local-dir: ./dist/
          server-dir: ${{ secrets.SFTP_TARGET_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          dangerous-clean-slate: false
          dry-run: false
      - name: Verify deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            echo "Checking deployed files in ${{ secrets.SFTP_TARGET_DIR }}:"
            ls -la ${{ secrets.SFTP_TARGET_DIR }}
            echo "Verifying .htaccess file:"
            test -f ${{ secrets.SFTP_TARGET_DIR }}/.htaccess && echo "✓ .htaccess deployed successfully" || echo "✗ .htaccess missing on server"
            echo "Contents of .htaccess on server:"
            cat ${{ secrets.SFTP_TARGET_DIR }}/.htaccess || echo "Could not read .htaccess from server"
