name: Hostinger Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy PHP files to dist
        run: |
          cp index.php dist/
          cp composer.json dist/
          cp composer.lock dist/

      - name: Deploy to Hostinger via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: dist/
          server-dir: ${{ secrets.FTP_TARGET_DIR }}
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            **/.env*
